apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.service.name" . }}
spec:
  selector:
    app: {{ .Values.backend.selname }}
  type: {{ .Values.backend.service.type}}
  ports:
    - port: {{ .Values.backend.service.port}}
      targetPort: {{ .Values.backend.service.targetPort}}