apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.service.name" . }}
spec:
  selector:
    app: {{ .Values.frontend.selname }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}
