apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hpa.name" . }}
spec:
  minReplicas: {{ .Values.hpa.minReplicas}}
  maxReplicas: {{ .Values.hpa.maxReplicas}}
  metrics:
    - resource:
        name: {{ .Values.hpa.metrics.name }}
        target: 
          averageUtilization: {{ .Values.hpa.metrics.target.averageUtilization }}
          type: {{ .Values.hpa.metrics.target.type }}
      type: {{ .Values.hpa.metrics.type }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: {{ .Values.hpa.scaletarget }}