apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-stress-job
spec:
  template:
    metadata:
      name: cpu-stress-pod
    spec:
      containers:
      - name: stress-container
        image: progrium/stress
        command: ["stress"]
        args: ["--cpu", "2", "--timeout", "3s"]  
      restartPolicy: Never
